# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en-US"

early_access: true

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  path_filters:
    - "!**/*.lock"
    - "!**/package-lock.json"
    - "!**/yarn.lock"
    - "!**/*.min.js"
    - "!**/*.min.css"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/.next/**"
    - "!**/node_modules/**"

  path_instructions:
    - path: "cli/**"
      instructions: |
        Review the CLI code for:
        - Proper error handling and user-friendly error messages
        - Consistent command structure following Cline CLI patterns
        - Secure handling of API keys and tokens
        - TypeScript best practices

    - path: "dashboard/**"
      instructions: |
        Review the dashboard code for:
        - React/Next.js best practices
        - Proper use of server/client components
        - Accessibility (a11y) considerations
        - Performance optimizations
        - Responsive design patterns

    - path: "kestra/**"
      instructions: |
        Review Kestra workflow definitions for:
        - Proper YAML syntax and structure
        - Efficient task orchestration
        - Error handling and retry logic
        - Security best practices for secrets

    - path: "oumi/**"
      instructions: |
        Review Oumi training code for:
        - Proper use of GRPO/RL techniques
        - Data preprocessing best practices
        - Model evaluation metrics
        - Memory efficiency for CPU training

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  jira:
    project_keys: []
  pull_requests:
    scope: "auto"
