id: review-analyzer-http
namespace: review-forge
description: |
  AI Agent workflow to analyze PR reviews and generate quality scores (HTTP-based, no Docker).
  Available free models (change if rate limited - 429):
  - mistralai/devstral-2512:free (default)
  - nex-agi/deepseek-v3.1-nex-n1:free
  - amazon/nova-2-lite-v1:free
  - allenai/olmo-3-32b-think:free
  - openai/gpt-oss-120b:free
  - qwen/qwen3-coder:free
  - google/gemma-3n-e2b-it:free
  - google/gemma-3n-e4b-it:free
  - meta-llama/llama-3.3-70b-instruct:free

inputs:
  - id: github_owner
    type: STRING
    defaults: "mohamedkaseem"
  - id: github_repo
    type: STRING
    defaults: "self-healing-agent"
  - id: pr_number
    type: INT
    required: true
  - id: github_token
    type: STRING
    required: true
    description: GitHub Personal Access Token
  - id: openrouter_api_key
    type: STRING
    required: true
    description: OpenRouter API Key

tasks:
  - id: fetch_pr_details
    type: io.kestra.plugin.core.http.Request
    description: Fetch PR details from GitHub
    uri: "https://api.github.com/repos/{{inputs.github_owner}}/{{inputs.github_repo}}/pulls/{{inputs.pr_number}}"
    method: GET
    headers:
      Authorization: "token {{inputs.github_token}}"
      Accept: "application/vnd.github.v3+json"

  - id: fetch_pr_reviews
    type: io.kestra.plugin.core.http.Request
    description: Fetch PR reviews from GitHub
    uri: "https://api.github.com/repos/{{inputs.github_owner}}/{{inputs.github_repo}}/pulls/{{inputs.pr_number}}/reviews"
    method: GET
    headers:
      Authorization: "token {{inputs.github_token}}"
      Accept: "application/vnd.github.v3+json"

  - id: fetch_pr_comments
    type: io.kestra.plugin.core.http.Request
    description: Fetch PR review comments from GitHub
    uri: "https://api.github.com/repos/{{inputs.github_owner}}/{{inputs.github_repo}}/pulls/{{inputs.pr_number}}/comments"
    method: GET
    headers:
      Authorization: "token {{inputs.github_token}}"
      Accept: "application/vnd.github.v3+json"

  - id: log_github_data
    type: io.kestra.plugin.core.log.Log
    description: Log the GitHub data retrieved
    message: |
      PR Details: {{outputs.fetch_pr_details.body}}
      Reviews: {{outputs.fetch_pr_reviews.body}}
      Comments: {{outputs.fetch_pr_comments.body}}

  - id: ai_analyze_reviews
    type: io.kestra.plugin.core.http.Request
    description: AI Agent analyzes and scores reviews using OpenRouter
    uri: "https://openrouter.ai/api/v1/chat/completions"
    method: POST
    headers:
      Authorization: "Bearer {{inputs.openrouter_api_key}}"
      Content-Type: "application/json"
      HTTP-Referer: "https://review-forge.dev"
      X-Title: "Review-Forge Kestra"
    contentType: "application/json"
    body: |
      {
        "model": "mistralai/devstral-2512:free",
        "messages": [
          {
            "role": "system",
            "content": "You are a code review quality analyst. Analyze the quality of code reviews and respond ONLY with valid JSON."
          },
          {
            "role": "user",
            "content": {{ ("Analyze the quality of code reviews for PR #" ~ inputs.pr_number ~ " from " ~ inputs.github_owner ~ "/" ~ inputs.github_repo ~ ". Here is the actual PR data: " ~ outputs.fetch_pr_details.body ~ " Reviews: " ~ outputs.fetch_pr_reviews.body ~ " Comments: " ~ outputs.fetch_pr_comments.body ~ " Score the reviews on these dimensions (0-25 each): 1) Clarity 2) Completeness 3) Actionability 4) Constructiveness. Respond with JSON: {pr_number: " ~ inputs.pr_number ~ ", overall_score: 0-100, clarity: 0-25, completeness: 0-25, actionability: 0-25, constructiveness: 0-25, summary: text, recommendations: [items], action: approve|suggest_improvements|flag_for_review}") | json }}
          }
        ],
        "temperature": 0.3,
        "max_tokens": 2048
      }

  - id: log_results
    type: io.kestra.plugin.core.log.Log
    description: Log the analysis results
    message: |
      ============================================================
      📊 REVIEW QUALITY ANALYSIS REPORT
      ============================================================
      Repository: {{inputs.github_owner}}/{{inputs.github_repo}}
      PR #{{inputs.pr_number}}
      
      📈 GitHub Data Retrieved:
         - PR Details: ✅
         - Reviews: ✅
         - Comments: ✅
      
      🤖 AI Quality Analysis:
      {{outputs.ai_analyze_reviews.body}}
      ============================================================

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "review-analyzer-http"
